### ISSUE TITLE
./stella-bridge.sh: line 149: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by toontong** [StudioEtrange/ngrok-build#1]
## 1. synax:

   ./stella-bridge.sh: line 149: syntax error near unexpected token `fi'
## 2. when I fix it, another error appear:

   ./stella-bridge.sh: line 76: /home/hct/ngrok-build/../stella/conf.sh: No such file or directory
./stella-bridge.sh: line 81: __stella_requirement: command not found
/home/hct/ngrok-build/stella-link.sh: line 25: /home/hct/ngrok-build/../stella/conf.sh: No such file or directory
/home/hct/ngrok-build/stella-link.sh: line 26: __init_stella_env: command not found

**Comment by StudioEtrange** [comment]
Thx
Should be fixed now

Tell me if it is ok for you now
