### ISSUE TITLE
unable to detect version control system for code.google.com/ path

### ISSUE THREAD

**Issue by jwanhussin** [StudioEtrange/ngrok-build#2]
Getting this error when building ngrokd on ubuntu 14.04:

---

*\* build server for all platforms
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/client/assets/assets_release.go \
        assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/server/assets/assets_release.go \
        assets/server/...
go get -tags 'release' -d -v ngrok/...
package code.google.com/p/log4go: unable to detect version control system for code.google.com/ path
make: **\* [deps] Error 1
*\* build client for all platforms
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/client/assets/assets_release.go \
        assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/server/assets/assets_release.go \
        assets/server/...
go get -tags 'release' -d -v ngrok/...
package code.google.com/p/log4go: unable to detect version control system for code.google.com/ path
make: **\* [deps] Error 1

---

Apparently google code closed down..?
 [http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html]

**Comment by StudioEtrange** [comment]
There is a PR on upstream ngrok about this
https://github.com/inconshreveable/ngrok/pull/308

I think I will wait a little bit for its merge

**Comment by StudioEtrange** [comment]
Ok, the PR was merged upstream https://github.com/inconshreveable/ngrok/pull/308

But it is not released in a package yet (it is not included in 1.7.1)
I will generate patch by myself

**Comment by StudioEtrange** [comment]
Now resolved.
A patch including fix for google code logger repo is now applied on source code
